// محتوى اللعبة التعليمية لتعلم اللغة الفارسية
// كل عنصر يحتوي على: الفارسية، النطق باللاتينية، المعنى بالعربية

export const ALPHABET = [
  { letter: "ا", name: "alef",       sound: "â / a",  example: "آب",     exTr: "âb",        exMeaning: "ماء" },
  { letter: "ب", name: "be",         sound: "b",      example: "باد",    exTr: "bâd",        exMeaning: "ريح" },
  { letter: "پ", name: "pe",         sound: "p",      example: "پدر",    exTr: "pedar",      exMeaning: "أب" },
  { letter: "ت", name: "te",         sound: "t",      example: "توپ",    exTr: "toop",       exMeaning: "كرة" },
  { letter: "ث", name: "se",         sound: "s",      example: "مثل",    exTr: "mesl",       exMeaning: "مثل" },
  { letter: "ج", name: "jim",        sound: "j",      example: "جان",    exTr: "jân",        exMeaning: "روح/عزيزي" },
  { letter: "چ", name: "che",        sound: "ch",     example: "چای",    exTr: "châi",       exMeaning: "شاي" },
  { letter: "ح", name: "he‑ye jimi", sound: "h",      example: "حال",    exTr: "hâl",        exMeaning: "حال" },
  { letter: "خ", name: "khe",        sound: "kh",     example: "خانه",   exTr: "khâne",      exMeaning: "بيت" },
  { letter: "د", name: "dâl",        sound: "d",      example: "در",     exTr: "dar",        exMeaning: "باب" },
  { letter: "ذ", name: "zâl",        sound: "z",      example: "ذهن",    exTr: "zehn",       exMeaning: "ذهن" },
  { letter: "ر", name: "re",         sound: "r",      example: "روز",    exTr: "rooz",       exMeaning: "يوم" },
  { letter: "ز", name: "ze",         sound: "z",      example: "زرد",    exTr: "zard",       exMeaning: "أصفر" },
  { letter: "ژ", name: "zhe",        sound: "zh",     example: "ژاله",   exTr: "zhâle",      exMeaning: "ندى" },
  { letter: "س", name: "sin",        sound: "s",      example: "سلام",   exTr: "salâm",      exMeaning: "مرحبا" },
  { letter: "ش", name: "shin",       sound: "sh",     example: "شب",     exTr: "shab",       exMeaning: "ليل" },
  { letter: "ص", name: "sâd",        sound: "s",      example: "صبح",    exTr: "sobh",       exMeaning: "صباح" },
  { letter: "ض", name: "zâd",        sound: "z",      example: "ضعیف",   exTr: "za'if",      exMeaning: "ضعيف" },
  { letter: "ط", name: "tâ",         sound: "t",      example: "طلا",    exTr: "talâ",       exMeaning: "ذهب" },
  { letter: "ظ", name: "zâ",         sound: "z",      example: "ظهر",    exTr: "zohr",       exMeaning: "ظهر" },
  { letter: "ع", name: "eyn",        sound: "'",      example: "علم",    exTr: "elm",        exMeaning: "علم" },
  { letter: "غ", name: "gheyn",      sound: "gh",     example: "غذا",    exTr: "ghazâ",      exMeaning: "طعام" },
  { letter: "ف", name: "fe",         sound: "f",      example: "فردا",   exTr: "fardâ",      exMeaning: "غدا" },
  { letter: "ق", name: "qâf",        sound: "q",      example: "قلب",    exTr: "qalb",       exMeaning: "قلب" },
  { letter: "ک", name: "kâf",        sound: "k",      example: "کتاب",   exTr: "ketâb",      exMeaning: "كتاب" },
  { letter: "گ", name: "gâf",        sound: "g",      example: "گل",     exTr: "gol",        exMeaning: "زهرة" },
  { letter: "ل", name: "lâm",        sound: "l",      example: "لب",     exTr: "lab",        exMeaning: "شفة" },
  { letter: "م", name: "mim",        sound: "m",      example: "مادر",   exTr: "mâdar",      exMeaning: "أم" },
  { letter: "ن", name: "nun",        sound: "n",      example: "نان",    exTr: "nân",        exMeaning: "خبز" },
  { letter: "و", name: "vâv",        sound: "v / u",  example: "ورزش",   exTr: "varzesh",    exMeaning: "رياضة" },
  { letter: "ه", name: "he",         sound: "h",      example: "هوا",    exTr: "havâ",       exMeaning: "جو" },
  { letter: "ی", name: "ye",         sound: "y / i",  example: "یخ",     exTr: "yakh",       exMeaning: "ثلج" },
];

export const VOCAB_CATEGORIES = [
  {
    id: "greetings",
    title: "التحيات",
    icon: "☾",
    words: [
      { fa: "سلام", tr: "salâm", ar: "مرحبا" },
      { fa: "خداحافظ", tr: "khodâhâfez", ar: "مع السلامة" },
      { fa: "صبح بخیر", tr: "sobh bekheir", ar: "صباح الخير" },
      { fa: "شب بخیر", tr: "shab bekheir", ar: "تصبح على خير" },
      { fa: "متشکرم", tr: "motshakeram", ar: "شكرا" },
      { fa: "خواهش می‌کنم", tr: "khâhesh mikonam", ar: "عفوا" },
      { fa: "بله", tr: "bale", ar: "نعم" },
      { fa: "نه", tr: "na", ar: "لا" },
    ],
  },
  {
    id: "numbers",
    title: "الأرقام",
    icon: "٭",
    words: [
      { fa: "صفر", tr: "sefr", ar: "صفر" },
      { fa: "یک", tr: "yek", ar: "واحد" },
      { fa: "دو", tr: "do", ar: "اثنان" },
      { fa: "سه", tr: "se", ar: "ثلاثة" },
      { fa: "چهار", tr: "chahâr", ar: "أربعة" },
      { fa: "پنج", tr: "panj", ar: "خمسة" },
      { fa: "شش", tr: "shesh", ar: "ستة" },
      { fa: "هفت", tr: "haft", ar: "سبعة" },
      { fa: "هشت", tr: "hasht", ar: "ثمانية" },
      { fa: "نه", tr: "noh", ar: "تسعة" },
      { fa: "ده", tr: "dah", ar: "عشرة" },
    ],
  },
  {
    id: "family",
    title: "العائلة",
    icon: "❖",
    words: [
      { fa: "پدر", tr: "pedar", ar: "أب" },
      { fa: "مادر", tr: "mâdar", ar: "أم" },
      { fa: "برادر", tr: "barâdar", ar: "أخ" },
      { fa: "خواهر", tr: "khâhar", ar: "أخت" },
      { fa: "پسر", tr: "pesar", ar: "ابن" },
      { fa: "دختر", tr: "dokhtar", ar: "ابنة" },
      { fa: "پدربزرگ", tr: "pedar bozorg", ar: "جد" },
      { fa: "مادربزرگ", tr: "mâdar bozorg", ar: "جدة" },
    ],
  },
  {
    id: "colors",
    title: "الألوان",
    icon: "◈",
    words: [
      { fa: "قرمز", tr: "qermez", ar: "أحمر" },
      { fa: "آبی", tr: "âbi", ar: "أزرق" },
      { fa: "سبز", tr: "sabz", ar: "أخضر" },
      { fa: "زرد", tr: "zard", ar: "أصفر" },
      { fa: "سفید", tr: "sefid", ar: "أبيض" },
      { fa: "سیاه", tr: "siyâh", ar: "أسود" },
      { fa: "نارنجی", tr: "nârenji", ar: "برتقالي" },
      { fa: "بنفش", tr: "banafsh", ar: "بنفسجي" },
    ],
  },
  {
    id: "days",
    title: "أيام الأسبوع",
    icon: "☽",
    words: [
      { fa: "شنبه", tr: "shanbe", ar: "السبت" },
      { fa: "یکشنبه", tr: "yekshanbe", ar: "الأحد" },
      { fa: "دوشنبه", tr: "doshanbe", ar: "الإثنين" },
      { fa: "سه‌شنبه", tr: "seshanbe", ar: "الثلاثاء" },
      { fa: "چهارشنبه", tr: "chahârshanbe", ar: "الأربعاء" },
      { fa: "پنج‌شنبه", tr: "panjshanbe", ar: "الخميس" },
      { fa: "جمعه", tr: "jom'e", ar: "الجمعة" },
    ],
  },
  {
    id: "phrases",
    title: "عبارات شائعة",
    icon: "✦",
    words: [
      { fa: "اسم شما چیست؟", tr: "esme shomâ chist?", ar: "ما اسمك؟" },
      { fa: "حالت چطوره؟", tr: "hâlet chetore?", ar: "كيف حالك؟" },
      { fa: "من خوبم", tr: "man khoobam", ar: "أنا بخير" },
      { fa: "دوستت دارم", tr: "doostet dâram", ar: "أحبك" },
      { fa: "ممنونم", tr: "mamnoonam", ar: "شكرا لك" },
      { fa: "کجا می‌روی؟", tr: "kojâ miravi?", ar: "إلى أين تذهب؟" },
      { fa: "چند سالته؟", tr: "chand sâlete?", ar: "كم عمرك؟" },
      { fa: "خیلی خوب", tr: "kheili khoob", ar: "جيد جدا" },
    ],
  },
];

export const SENTENCES = [
  { fa: "سلام، حال شما چطور است؟", tr: "Salâm, hâle shomâ chetor ast?", ar: "مرحبا، كيف حالك؟" },
  { fa: "اسم من علی است.", tr: "Esme man Ali ast.", ar: "اسمي علي." },
  { fa: "من از عراق هستم.", tr: "Man az Erâgh hastam.", ar: "أنا من العراق." },
  { fa: "امروز هوا خوب است.", tr: "Emrooz havâ khoob ast.", ar: "الجو جميل اليوم." },
  { fa: "من فارسی یاد می‌گیرم.", tr: "Man fârsi yâd migiram.", ar: "أنا أتعلم الفارسية." },
  { fa: "این کتاب من است.", tr: "In ketâbe man ast.", ar: "هذا كتابي." },
  { fa: "خانه‌ی ما بزرگ است.", tr: "Khâneye mâ bozorg ast.", ar: "بيتنا كبير." },
  { fa: "من گرسنه هستم.", tr: "Man gorosne hastam.", ar: "أنا جائع." },
  { fa: "لطفا کمکم کنید.", tr: "Lotfan komakam konid.", ar: "من فضلك ساعدني." },
  { fa: "ساعت چند است؟", tr: "Sâat chand ast?", ar: "كم الساعة؟" },
  { fa: "من دوست دارم فارسی صحبت کنم.", tr: "Man doost dâram fârsi sohbat konam.", ar: "أحب أن أتحدث الفارسية." },
  { fa: "فردا می‌بینمت.", tr: "Fardâ mibinamet.", ar: "أراك غدا." },
  { fa: "این خیلی خوشمزه است.", tr: "In kheili khoshmaze ast.", ar: "هذا لذيذ جدا." },
  { fa: "من باید بروم.", tr: "Man bâyad beravam.", ar: "يجب أن أذهب." },
  { fa: "خوش آمدید.", tr: "Khosh âmadid.", ar: "أهلا وسهلا بك." },
];

// وحدات الدروس المصغرة: كل درس يقدّم عناصر جديدة ثم تمرين عليها
export const LESSONS = [
  { id: "l1", title: "الدرس الأول: التحية", type: "vocab", categoryId: "greetings", xp: 20 },
  { id: "l2", title: "الدرس الثاني: الأرقام 0-10", type: "vocab", categoryId: "numbers", xp: 20 },
  { id: "l3", title: "الدرس الثالث: أبجدية (ا-ج)", type: "alphabet", range: [0, 6], xp: 20 },
  { id: "l4", title: "الدرس الرابع: العائلة", type: "vocab", categoryId: "family", xp: 20 },
  { id: "l5", title: "الدرس الخامس: أبجدية (چ-ز)", type: "alphabet", range: [6, 13], xp: 20 },
  { id: "l6", title: "الدرس السادس: الألوان", type: "vocab", categoryId: "colors", xp: 20 },
  { id: "l7", title: "الدرس السابع: أيام الأسبوع", type: "vocab", categoryId: "days", xp: 20 },
  { id: "l8", title: "الدرس الثامن: أبجدية (ژ-ص)", type: "alphabet", range: [13, 18], xp: 20 },
  { id: "l9", title: "الدرس التاسع: عبارات شائعة", type: "vocab", categoryId: "phrases", xp: 20 },
  { id: "l10", title: "الدرس العاشر: جمل بسيطة", type: "sentences", range: [0, 6], xp: 25 },
  { id: "l11", title: "الدرس الحادي عشر: أبجدية (ض-ق)", type: "alphabet", range: [18, 24], xp: 20 },
  { id: "l12", title: "الدرس الثاني عشر: أبجدية (ک-ی)", type: "alphabet", range: [24, 32], xp: 20 },
  { id: "l13", title: "الدرس الثالث عشر: جمل متقدمة", type: "sentences", range: [6, 15], xp: 25 },
];
